pipeline {
    agent any
    tools {
        maven 'maven-3.9.2'
    }
    stages {
        stage("Clean Up") {
            steps {
                deleteDir()
            }
        }
        stage("Clone Repo") {
            steps {
                sh 'git clone https://github.com/jenkins-docs/simple-java-maven-app.git'
            }
        }
        stage("Build") {
            steps {
                dir("simple-java-maven-app") {
                    sh 'mvn clean install'
                }
            }
        }
        stage("Test") {
            steps {
                dir("simple-java-maven-app") {
                    sh 'mvn test'
                }
            }
        }
    }
}

